spring.application.name=gps-backend

# Desactivar la autoconfiguración de base de datos mientras se prueba el GPS
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

# Puerto HTTP de Spring Boot
server.port=8080